version: '3.3'
services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    tty: true
    ports:
      - "5454:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - agrovence-network

  agrovenceapi:
    build: .
    command: yarn production
    volumes:
      - ./:/usr/src
    ports:
      - "4999:3333"
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      APP_NAME: ${APP_NAME}
      APP_URL: ${APP_URL}
      CACHE_VIEWS: ${CACHE_VIEWS}
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      HASH_DRIVER: ${HASH_DRIVER}

    depends_on:
      - db
    networks:
      - agrovence-network

  web:
    build:
      context: ./
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - /etc/letsencrypt/archive/agrovence.com.br:/etc/letsencrypt/live/agrovence.com.br
    ports:
      - 80:80
      - 443:443
    networks:
      - agrovence-network

networks:
  agrovence-network:
    driver: bridge

volumes:
  postgres-data:
  agrovenceapi-data:
